#!/usr/bin/python

ifile = open("input-fcfs.txt")

nqueue = []
ready_queue = []
running_process = {}
timer = 0


nqueue = [
    {'PID': line.split(' ')[0], 'arr_time': int(line.split(' ')[1]), 'burst_time': int(line.split(' ')[2])}
    for line in ifile.read().splitlines()
    ]

for process in nqueue:
    print(process)


while len(nqueue) > 0 or len(ready_queue) > 0:
    
    if len(ready_queue) > 0:
        running_process = ready_queue[0]
    else:
       
        for new in nqueue:
            if new['arr_time'] <= timer:
                ready_queue.append(new)
        
        
        for r in ready_queue:
            if r in nqueue:
                nqueue.remove(r)

        timer += 1

        continue

    i = 0
    while i < running_process['burst_time']:
        timer += 1

        for new in nqueue:
            if new['arr_time'] <= timer:
                ready_queue.append(new)
        
       
        for r in ready_queue:
            if r in nqueue:
                nqueue.remove(r)
        i += 1

    print("PID: {}, AT: {}, FT: {}".format(running_process['PID'], running_process['arr_time'], timer - 1))
    ready_queue.remove(running_process)
